# Author: Nuncvc1v0

# Custom variables for use across all Hyprland configs

$mainMod = SUPER                                          # Main modifier key (SUPER/ALT/CTRL/SHIFT)

$terminal    = wezterm                                    # Terminal emulator
$fileManager = wezterm -e yazi                            # File manager (TUI in terminal)
$menu        = anyrun                                     # Application launcher
$browser     = firefox                                    # Web browser
$editor      = nvim                                       # Text editor
